Adding Egg Model Files to the branch Egg model
equinor/flownet-testdata pull request #2
Opened 2020-08-07 07:28 UTC by tayloris

I'm sharing Egg model input files.

Configuration file is also included but I'll be working on it to improve the history match.

2020-08-13 18:53 UTC, tayloris commented
I think it is ready for review

2020-08-24 09:32 UTC, wouterjdb requested changes
Two additional points:

- Please remove the SINTEF logo
- Please rename `egg_model/input_model/Egg_model.tar.xz` to `egg_model/input_model/Egg_model.tar.gz`

2020-08-24 09:32 UTC, wouterjdb commented on egg_model/README.md
> +</p>
```suggestion
 The Egg model  is a synthetic reservoir model developed by [J. D. Jansen et al. [1,2]](https://rmets.onlinelibrary.wiley.com/doi/pdf/10.1002/gdj3.21). 
```

2020-08-24 09:52 UTC, wouterjdb approved these changes

2020-08-24 09:53 UTC, merged